### ISSUE TITLE
shebang doesn't work with scala 2.13.6

### ISSUE THREAD

**Issue by lrytz** [VirtusLab/scala-cli#166]
```
➜ cat A.scala
#!/usr/bin/env scala-cli
object Main {
  def main(args: Array[String]): Unit = {
    println(s"Hello ${args(0)}")
  }
}

➜ ./A.scala -- World
Hello World

➜ scala-cli ./A.scala -- World
Hello World

➜ ./A.scala --scala-version 2.13.6 -- World
Compiling project (Scala 2.13.6, JVM)
[error] ./A.scala:1:1: expected class or object definition
[error] ^
Error compiling project (Scala 2.13.6, JVM)
Compilation failed

➜ scala-cli --scala-version 2.13.6 ./A.scala -- World
Compiling project (Scala 2.13.6, JVM)
[error] ./A.scala:1:1: expected class or object definition
[error] ^
Error compiling project (Scala 2.13.6, JVM)
Compilation failed
```

**Comment by alexarchambault** [comment]
At first, I'd say requiring a `--` before user arguments is an overlook (on our side). The scala version can be specified with a `// using scala 2.13` before any import or package… but it seems it doesn't work either with Scala CLI `0.0.4` :|
