### ISSUE TITLE
`Compilation failed` message with no context (2.13.7 issue)

### ISSUE THREAD

**Issue by ckipp01** [VirtusLab/scala-cli#324]
Given the following snippet:

```scala
// using scala 2.13
import $dep.`com.lihaoyi::requests:0.6.9`

object LatestVersion extends App {

  println("hello")

}
```

When the user tries to run this they just see:

```
❯ scala-cli run LatestVersion.scala
Compiling project (Scala 2.13.7, JVM)
Error compiling project (Scala 2.13.7, JVM)
Compilation failed
```
Adding a single `-v` shows the same thing. Two `-v` start to show more info, but I think a user shouldn't ever have to dive into more verbose messages to try and understand why this isn't working. Note that this works if you try `2.13.6`, but just having `2.13` is defaulting to `2.13.7` at the moment which isn't working. I can forsee a user having a script that is working one day, a new release comes out, and without them realizing it, the version is bumped and their script is no longer working.

**Comment by ckipp01** [comment]
Actually I realize that this is probably a Bloop issue not working with 2.13 https://github.com/scalacenter/bloop/issues/1598. I'll leave this open just to track. Plus, I think it these situations it might be nice to give the user at least some sort of indication what is going wrong.

**Comment by carueda** [comment]
fwiw, just tried this (on a mac, with a just `brew`-installed `scala-cli`), and all good, surely because of some fix in bloop

```
$ scala-cli version
0.0.7

$ scala-cli issue324.scala
Compiling project (Scala 2.13.7, JVM)
Compiled project (Scala 2.13.7, JVM)
hello
```

**Comment by lwronski** [comment]
Hi @ckipp01, thank you for reporting. 

It was caused by a bug in bloop after release scala `2.13.7`.  We fixed it in `scala-cli` 0.0.8 [#339 ](https://github.com/VirtusLab/scala-cli/pull/339) updating bloop version.

If problem is not fixed after the update, please let us know and we will open this issue.
