### ISSUE TITLE
Scala code won't compile on Scala 2.12.x < 2.12.5 because of the `-release` compiler option

### ISSUE THREAD

**Issue by Gedochao** [VirtusLab/scala-cli#1373]
**Version(s)**
0.1.14

**To Reproduce**
```bash
▶ scala-cli -S 2.12.2 -e 'println("Hello")'                            
Compiling project (Scala 2.12.2, JVM)
Error: bad option: '-release'
Error compiling project (Scala 2.12.2, JVM)
Compilation failed
```
