### ISSUE TITLE
`NoClassDefFoundError` since version 0.2.0 when using aarch64 Linux

### ISSUE THREAD

**Issue by mkurz** [VirtusLab/scala-cli#1972]
Running Linux aarch64.

I have scala-cli installed via sdkman:
```sh
$ sdk list scalacli
================================================================================
Available Scalacli Versions
================================================================================
 > * 0.2.1                                                                      
     0.2.0                                                                      
   * 0.1.20                                                                     

================================================================================
+ - local version
* - installed
> - currently in use
================================================================================

```
Latest 0.2.1 doesn't work:
```sh
$ scala-cli
Exception in thread "main" java.lang.NoClassDefFoundError: com.oracle.svm.core.JavaMainWrapper
        at scala.cli.internal.Argv0.get(Argv0.scala:16)
        at scala.cli.ScalaCli$.<clinit>(ScalaCli.scala:28)
        at scala.cli.ScalaCli.main(ScalaCli.scala)
```

It was working with 0.1.20 however (but also not with 0.2.0.

**Comment by lwronski** [comment]
@mkurz Thanks for reporting, it should be fixed from the next release of Scala CLI. 

You can now try the nightly version of Scala CLI for aarch64. It is available [here](https://github.com/VirtusLab/scala-cli/releases/download/nightly/scala-cli-aarch64-pc-linux.gz).

**Comment by mkurz** [comment]
@lwronski It works:
```sh
mkurz@mkurz-macbook-pro:/tmp/scala-cli-test$ ./scala-cli-aarch64-pc-linux -version
Scala CLI version: 0.2.1-60-gf86e7cd1-SNAPSHOT
Scala version (default): 3.2.2
mkurz@mkurz-macbook-pro:/tmp/scala-cli-test$ ./scala-cli-aarch64-pc-linux 
Welcome to Scala 3.2.2 (11.0.18, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                                                                                    
scala> val foo = "bar"
val foo: String = bar
                                                                                                                                                    
scala> println("Testing this awesome stuff")
Testing this awesome stuff
                                                                                                                                                    
scala> 
```
